FROM rust:1.67

ARG TWITCH_OAUTH_TOKEN
ARG TWITCH_CHANNEL_NAME
ARG TWITCH_BOT_NICK
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET
ARG WEB_URI
ARG AMQP_ADDR

WORKDIR /usr/src/myapp
COPY . .

RUN echo "TWITCH_CHANNEL_NAME: $TWITCH_CHANNEL_NAME"

ENV TWITCH_OAUTH_TOKEN=$TWITCH_OAUTH_TOKEN
ENV TWITCH_CHANNEL_NAME=$TWITCH_CHANNEL_NAME
ENV TWITCH_BOT_NICK=$TWITCH_BOT_NICK
ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
ENV WEB_URI=$WEB_URI
ENV AMQP_ADDR=$AMQP_ADDR

RUN cargo install --path .

CMD ["rust-ws"]